from typing import Any, Protocol

from motor.motor_asyncio import AsyncIOMotorClientSession


class MovieRepositoryProtocol(Protocol):
    async def insert_one(self, document: dict, session: AsyncIOMotorClientSession | None = None) -> str: ...
    async def find_by_movie_id(self, movie_id: str) -> dict | None: ...
    async def find_by_normalized_title(self, title: str) -> dict | None: ...
    async def search(self, query: str, skip: int, limit: int) -> list[dict]: ...
    async def find_latest(self, status: str, skip: int, limit: int) -> list[dict]: ...
    async def find_many(self, filter_: dict, projection: dict | None = None, skip: int = 0, limit: int = 20, sort: list[tuple[str, int]] | None = None, session: AsyncIOMotorClientSession | None = None) -> list[dict]: ...
    async def update_one(self, filter_: dict, update: dict, session: AsyncIOMotorClientSession | None = None) -> int: ...
    async def delete_one(self, filter_: dict, session: AsyncIOMotorClientSession | None = None) -> int: ...
    async def count(self, filter_: dict | None = None, session: AsyncIOMotorClientSession | None = None) -> int: ...
    async def exists(self, filter_: dict, session: AsyncIOMotorClientSession | None = None) -> bool: ...


class MovieFileRepositoryProtocol(Protocol):
    async def insert_one(self, document: dict, session: AsyncIOMotorClientSession | None = None) -> str: ...
    async def insert_many(self, documents: list[dict], session: AsyncIOMotorClientSession | None = None) -> list[str]: ...
    async def find_by_movie_id(self, movie_id: str) -> list[dict]: ...
    async def find_by_file_unique_id(self, file_unique_id: str) -> dict | None: ...
    async def delete_by_movie_id(self, movie_id: str) -> int: ...
    async def delete_one(self, filter_: dict, session: AsyncIOMotorClientSession | None = None) -> int: ...
    async def count(self, filter_: dict | None = None, session: AsyncIOMotorClientSession | None = None) -> int: ...


class SettingsRepositoryProtocol(Protocol):
    async def get(self, key: str) -> dict | None: ...
    async def set(self, key: str, value: Any, updated_by: int | None = None) -> None: ...
    async def get_all(self) -> list[dict]: ...
    async def insert_one(self, document: dict) -> str: ...


class RequestRepositoryProtocol(Protocol):
    async def insert_one(self, document: dict) -> str: ...
    async def find_by_movie_name(self, movie_name: str) -> dict | None: ...
    async def find_by_user_id(self, user_id: int) -> list[dict]: ...
    async def find_pending(self, skip: int, limit: int) -> list[dict]: ...
    async def mark_fulfilled(self, request_id: str, movie_id: str) -> int: ...
    async def increment_count(self, request_id: str) -> int: ...
    async def count(self, filter_: dict | None = None) -> int: ...


class UserRepositoryProtocol(Protocol):
    async def upsert_user(self, user_data: dict) -> None: ...
    async def find_by_user_id(self, user_id: int) -> dict | None: ...
    async def find_active(self, skip: int, limit: int) -> list[dict]: ...
    async def count(self, filter_: dict | None = None) -> int: ...


class AdminRepositoryProtocol(Protocol):
    async def insert_one(self, document: dict) -> str: ...
    async def find_by_user_id(self, user_id: int) -> dict | None: ...
    async def find_all_active(self) -> list[dict]: ...
    async def is_admin(self, user_id: int) -> bool: ...
    async def count(self) -> int: ...


class BroadcastRepositoryProtocol(Protocol):
    async def insert_one(self, document: dict) -> str: ...
    async def find_by_status(self, status: str) -> list[dict]: ...
    async def update_progress(self, broadcast_id: str, success: int, fail: int) -> int: ...
    async def count(self, filter_: dict | None = None) -> int: ...


class BackupRepositoryProtocol(Protocol):
    async def insert_one(self, document: dict) -> str: ...
    async def find_latest(self) -> dict | None: ...
    async def find_by_type(self, type_: str, limit: int) -> list[dict]: ...
    async def count(self, filter_: dict | None = None) -> int: ...


class HealthRepositoryProtocol(Protocol):
    async def insert_one(self, document: dict) -> str: ...
    async def find_latest_checks(self, component: str, limit: int) -> list[dict]: ...


class SessionRepositoryProtocol(Protocol):
    async def find_by_user_id(self, user_id: int) -> dict | None: ...
    async def cleanup_expired(self) -> int: ...
